########### SNS

variable "create_sns_topic" {
  description = "Whether to create the SNS topic"
  type        = bool
  default     = true
}

variable "create_delivery_status_logging" {
  description = "Whether to create the SNS topic"
  type        = bool
  default     = true
}

variable "name" {
  type        = string
  description = "The friendly name for the SNS topic. By default generated by Terraform."
  default     = null
}

variable "display_name" {
  type        = string
  description = " The display name for the SNS topic"
  default     = null
}

variable "policy" {
  type        = string
  description = " The fully-formed AWS policy as JSON. For more information about building AWS IAM policy documents with Terraform"
  default     = null
}

variable "delivery_policy" {
  type        = string
  description = " The SNS delivery policy"
  default     = null
}

variable "application_success_feedback_role_arn" {
  type        = string
  description = "The IAM role permitted to receive success feedback for this topic"
  default     = null
}

variable "application_success_feedback_sample_rate" {
  type        = string
  description = " Percentage of success to sample"
  default     = null
}

variable "application_failure_feedback_role_arn" {
  type        = string
  description = "IAM role for failure feedback"
  default     = null
}

variable "http_success_feedback_role_arn" {
  type        = string
  description = "The IAM role permitted to receive success feedback for this topic"
  default     = null
}

variable "http_success_feedback_sample_rate" {
  type        = string
  description = " Percentage of success to sample"
  default     = null
}

variable "http_failure_feedback_role_arn" {
  type        = string
  description = "IAM role for failure feedback"
  default     = null
}

variable "kms_master_key_id" {
  type        = string
  description = "The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK"
  default     = null
}

variable "lambda_success_feedback_role_arn" {
  type        = string
  description = "The IAM role permitted to receive success feedback for this topic"
  default     = null
}

variable "lambda_success_feedback_sample_rate" {
  type        = string
  description = "Percentage of success to sample"
  default     = null
}

variable "lambda_failure_feedback_role_arn" {
  type        = string
  description = "IAM role for failure feedback"
  default     = null
}

variable "sqs_success_feedback_role_arn" {
  type        = string
  description = "The IAM role permitted to receive success feedback for this topic"
  default     = null
}

variable "sqs_success_feedback_sample_rate" {
  type        = string
  description = "Percentage of success to sample"
  default     = null
}

variable "sqs_failure_feedback_role_arn" {
  type        = string
  description = "IAM role for failure feedback"
  default     = null
}

variable "tags" {
  type        = map(string)
  description = "Key-value map of resource tags"
  default = {

  }
}
